"""add column comments

Revision ID: ac0cbcadbda1
Revises: 0001
Create Date: 2026-05-15 16:39:10.459790
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ac0cbcadbda1'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark_index', 'index_code',
               existing_type=sa.VARCHAR(length=32),
               comment='指数代码，如 000300',
               existing_nullable=False)
    op.alter_column('benchmark_index', 'name_cn',
               existing_type=sa.VARCHAR(length=128),
               comment='指数中文名称，如 沪深300',
               existing_nullable=False)
    op.alter_column('benchmark_index', 'exchange',
               existing_type=sa.VARCHAR(length=16),
               comment='所属市场，CN=中国 A 股',
               existing_nullable=False,
               existing_server_default=sa.text("'CN'::character varying"))
    op.alter_column('benchmark_index', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmark_index', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='记录最后更新时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_daily_bar', 'id',
               existing_type=sa.INTEGER(),
               comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_daily_bar', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('etf_daily_bar', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment='ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('etf_daily_bar', 'open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='开盘价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'high_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最高价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'low_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最低价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='收盘价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'prev_close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='前收盘价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'change_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='涨跌幅，单位 %，如 1.23 表示涨 1.23%',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成交量，单位 手（100 股）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'turnover',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成交额，单位 元',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'amplitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='振幅，单位 %',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment='数据来源，tencent=腾讯，stub=占位数据',
               existing_nullable=False,
               existing_server_default=sa.text("'stub'::character varying"))
    op.alter_column('etf_daily_bar', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='数据入库时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_daily_share', 'id',
               existing_type=sa.INTEGER(),
               comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_daily_share', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('etf_daily_share', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment='ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('etf_daily_share', 'shares_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总份额，单位 亿份',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'shares_delta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='当日份额变化量，单位 亿份，正=申购，负=赎回',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'shares_delta_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='当日份额变化率，单位 %',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'nav',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='单位净值，单位 元/份',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'aum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='资产管理规模（AUM），单位 亿元',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment='数据来源，eastmoney=东方财富，stub=占位数据',
               existing_nullable=False,
               existing_server_default=sa.text("'stub'::character varying"))
    op.alter_column('etf_daily_share', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='数据入库时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_factor_value', 'id',
               existing_type=sa.INTEGER(),
               comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_factor_value', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('etf_factor_value', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment='ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('etf_factor_value', 'factor_id',
               existing_type=sa.VARCHAR(length=64),
               comment='因子 ID，外键关联 factor_definition',
               existing_nullable=False)
    op.alter_column('etf_factor_value', 'factor_value_numeric',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='因子数值，如量比 1.92、概率得分 78.5',
               existing_nullable=True)
    op.alter_column('etf_factor_value', 'factor_value_text',
               existing_type=sa.VARCHAR(length=128),
               comment='因子文本值，用于枚举类因子',
               existing_nullable=True)
    op.alter_column('etf_factor_value', 'factor_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='因子计算中间数据，用于调试和解释',
               existing_nullable=True)
    op.alter_column('etf_factor_value', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment='产生该因子值的策略 ID，NULL 表示通用因子',
               existing_nullable=True)
    op.alter_column('etf_signal', 'id',
               existing_type=sa.INTEGER(),
               comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_signal', 'trade_date',
               existing_type=sa.DATE(),
               comment='信号对应的交易日期',
               existing_nullable=False)
    op.alter_column('etf_signal', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment='ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('etf_signal', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment='产生该信号的策略 ID',
               existing_nullable=False)
    op.alter_column('etf_signal', 'signal_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='综合得分，0-100，越高表示信号越强',
               existing_nullable=False)
    op.alter_column('etf_signal', 'signal_level',
               existing_type=sa.VARCHAR(length=32),
               comment='信号等级：HIGH≥70，MID 50-69，LOW<50',
               existing_nullable=False)
    op.alter_column('etf_signal', 'signal_label',
               existing_type=sa.VARCHAR(length=128),
               comment='信号中文标签，如 高确信、中等关注、正常',
               existing_nullable=False)
    op.alter_column('etf_signal', 'signal_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='信号计算明细，包含各因子得分等中间数据',
               existing_nullable=True)
    op.alter_column('etf_signal', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               comment='产生该信号的研究运行 ID，NULL 表示手动触发',
               existing_nullable=True)
    op.alter_column('etf_universe', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment='ETF 代码，如 510300',
               existing_nullable=False)
    op.alter_column('etf_universe', 'exchange',
               existing_type=sa.VARCHAR(length=8),
               comment='交易所代码，SSE=上交所，SZSE=深交所',
               existing_nullable=False)
    op.alter_column('etf_universe', 'name_cn',
               existing_type=sa.VARCHAR(length=128),
               comment='ETF 中文简称',
               existing_nullable=False)
    op.alter_column('etf_universe', 'fund_full_name',
               existing_type=sa.VARCHAR(length=256),
               comment='基金全称',
               existing_nullable=True)
    op.alter_column('etf_universe', 'tracking_index_code',
               existing_type=sa.VARCHAR(length=32),
               comment='跟踪指数代码，如 000300',
               existing_nullable=True)
    op.alter_column('etf_universe', 'tracking_index_name',
               existing_type=sa.VARCHAR(length=128),
               comment='跟踪指数名称，如 沪深300',
               existing_nullable=False)
    op.alter_column('etf_universe', 'fund_company',
               existing_type=sa.VARCHAR(length=128),
               comment='基金管理公司名称',
               existing_nullable=True)
    op.alter_column('etf_universe', 'listing_date',
               existing_type=sa.DATE(),
               comment='上市日期',
               existing_nullable=True)
    op.alter_column('etf_universe', 'delisting_date',
               existing_type=sa.DATE(),
               comment='退市日期，NULL 表示仍在交易',
               existing_nullable=True)
    op.alter_column('etf_universe', 'category',
               existing_type=sa.VARCHAR(length=64),
               comment='ETF 分类，如 broad_index=宽基指数',
               existing_nullable=False,
               existing_server_default=sa.text("'broad_index'::character varying"))
    op.alter_column('etf_universe', 'is_a_share_etf',
               existing_type=sa.BOOLEAN(),
               comment='是否为 A 股 ETF',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('etf_universe', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否在交易中，退市后置 False',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('etf_universe', 'data_source',
               existing_type=sa.VARCHAR(length=32),
               comment='数据来源，seed=内置种子数据',
               existing_nullable=False,
               existing_server_default=sa.text("'seed'::character varying"))
    op.alter_column('etf_universe', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_universe', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='记录最后更新时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factor_definition', 'factor_id',
               existing_type=sa.VARCHAR(length=64),
               comment='因子唯一标识，如 volume_ratio_20d',
               existing_nullable=False)
    op.alter_column('factor_definition', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment='因子中文名称，如 20日量比',
               existing_nullable=False)
    op.alter_column('factor_definition', 'description',
               existing_type=sa.TEXT(),
               comment='因子计算逻辑说明',
               existing_nullable=False)
    op.alter_column('factor_definition', 'version',
               existing_type=sa.VARCHAR(length=32),
               comment='因子版本号，遵循语义化版本',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0.0'::character varying"))
    op.alter_column('factor_definition', 'owner_plugin',
               existing_type=sa.VARCHAR(length=64),
               comment='定义该因子的策略插件 ID',
               existing_nullable=False)
    op.alter_column('index_daily_bar', 'id',
               existing_type=sa.INTEGER(),
               comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('index_daily_bar', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('index_daily_bar', 'index_code',
               existing_type=sa.VARCHAR(length=32),
               comment='指数代码，外键关联 benchmark_index',
               existing_nullable=False)
    op.alter_column('index_daily_bar', 'open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='开盘点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'high_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最高点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'low_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最低点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='收盘点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'prev_close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='前收盘点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'change_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='涨跌幅，单位 %',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成交量，单位 手',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'turnover',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成交额，单位 元',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment='数据来源，stub=占位数据',
               existing_nullable=False,
               existing_server_default=sa.text("'stub'::character varying"))
    op.alter_column('index_daily_bar', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='数据入库时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('research_run', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               comment='运行唯一 ID，UUID 格式',
               existing_nullable=False)
    op.alter_column('research_run', 'run_type',
               existing_type=sa.VARCHAR(length=64),
               comment='运行类型：daily_ingest=日频入库，strategy_run=策略运行，universe_refresh=标的刷新',
               existing_nullable=False)
    op.alter_column('research_run', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment='关联策略 ID，仅 strategy_run 类型有值',
               existing_nullable=True)
    op.alter_column('research_run', 'trade_date',
               existing_type=sa.DATE(),
               comment='运行对应的交易日期',
               existing_nullable=True)
    op.alter_column('research_run', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='运行状态：pending=待执行，running=执行中，success=成功，failed=失败',
               existing_nullable=False)
    op.alter_column('research_run', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='运行参数，JSON 格式',
               existing_nullable=True)
    op.alter_column('research_run', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='运行结果指标，如处理 ETF 数量、耗时等',
               existing_nullable=True)
    op.alter_column('research_run', 'error_message',
               existing_type=sa.TEXT(),
               comment='失败时的错误信息',
               existing_nullable=True)
    op.alter_column('research_run', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='运行开始时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('research_run', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='运行结束时间（UTC），NULL 表示未完成',
               existing_nullable=True)
    op.alter_column('research_run_item', 'id',
               existing_type=sa.INTEGER(),
               comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('research_run_item', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               comment='所属运行 ID，外键关联 research_run',
               existing_nullable=False)
    op.alter_column('research_run_item', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment='处理的 ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('research_run_item', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='单个 ETF 处理状态：success=成功，failed=失败，skipped=跳过',
               existing_nullable=False)
    op.alter_column('research_run_item', 'message',
               existing_type=sa.TEXT(),
               comment='处理结果说明或错误信息',
               existing_nullable=True)
    op.alter_column('research_run_item', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='单个 ETF 处理指标，如因子值、信号得分等',
               existing_nullable=True)
    op.alter_column('signal_definition', 'signal_id',
               existing_type=sa.VARCHAR(length=64),
               comment='信号唯一标识，如 three_factor_signal',
               existing_nullable=False)
    op.alter_column('signal_definition', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment='产生该信号的策略 ID',
               existing_nullable=False)
    op.alter_column('signal_definition', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment='信号中文名称',
               existing_nullable=False)
    op.alter_column('signal_definition', 'description',
               existing_type=sa.TEXT(),
               comment='信号含义和使用说明',
               existing_nullable=False)
    op.alter_column('signal_definition', 'version',
               existing_type=sa.VARCHAR(length=32),
               comment='信号版本号',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0.0'::character varying"))
    op.alter_column('source_payload_log', 'id',
               existing_type=sa.INTEGER(),
               comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('source_payload_log', 'source_name',
               existing_type=sa.VARCHAR(length=64),
               comment='数据源名称，如 tencent、eastmoney',
               existing_nullable=False)
    op.alter_column('source_payload_log', 'resource_type',
               existing_type=sa.VARCHAR(length=64),
               comment='资源类型，如 daily_bar、share_snapshot',
               existing_nullable=False)
    op.alter_column('source_payload_log', 'resource_key',
               existing_type=sa.VARCHAR(length=64),
               comment='资源标识，如 ETF 代码或指数代码',
               existing_nullable=False)
    op.alter_column('source_payload_log', 'trade_date',
               existing_type=sa.DATE(),
               comment='对应交易日期，NULL 表示非日频数据',
               existing_nullable=True)
    op.alter_column('source_payload_log', 'request_meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='请求元数据，如 URL、参数等',
               existing_nullable=True)
    op.alter_column('source_payload_log', 'response_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='原始响应数据，用于调试和审计',
               existing_nullable=True)
    op.alter_column('source_payload_log', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='数据拉取时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_plugin', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment='策略唯一标识，如 three_factor_guard',
               existing_nullable=False)
    op.alter_column('strategy_plugin', 'display_name',
               existing_type=sa.VARCHAR(length=128),
               comment='策略中文显示名称',
               existing_nullable=False)
    op.alter_column('strategy_plugin', 'plugin_module',
               existing_type=sa.VARCHAR(length=256),
               comment='插件 Python 模块路径',
               existing_nullable=False)
    op.alter_column('strategy_plugin', 'plugin_version',
               existing_type=sa.VARCHAR(length=32),
               comment='插件版本号',
               existing_nullable=False)
    op.alter_column('strategy_plugin', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='插件状态：active=启用，disabled=禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('strategy_plugin', 'default_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='策略默认参数，JSON 格式',
               existing_nullable=True)
    op.alter_column('strategy_plugin', 'result_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='策略输出结果的 JSON Schema 定义',
               existing_nullable=True)
    op.alter_column('strategy_plugin', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_plugin', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='记录最后更新时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy_plugin', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录最后更新时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_plugin', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_plugin', 'result_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='策略输出结果的 JSON Schema 定义',
               existing_nullable=True)
    op.alter_column('strategy_plugin', 'default_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='策略默认参数，JSON 格式',
               existing_nullable=True)
    op.alter_column('strategy_plugin', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='插件状态：active=启用，disabled=禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('strategy_plugin', 'plugin_version',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='插件版本号',
               existing_nullable=False)
    op.alter_column('strategy_plugin', 'plugin_module',
               existing_type=sa.VARCHAR(length=256),
               comment=None,
               existing_comment='插件 Python 模块路径',
               existing_nullable=False)
    op.alter_column('strategy_plugin', 'display_name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='策略中文显示名称',
               existing_nullable=False)
    op.alter_column('strategy_plugin', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='策略唯一标识，如 three_factor_guard',
               existing_nullable=False)
    op.alter_column('source_payload_log', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='数据拉取时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_payload_log', 'response_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='原始响应数据，用于调试和审计',
               existing_nullable=True)
    op.alter_column('source_payload_log', 'request_meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='请求元数据，如 URL、参数等',
               existing_nullable=True)
    op.alter_column('source_payload_log', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='对应交易日期，NULL 表示非日频数据',
               existing_nullable=True)
    op.alter_column('source_payload_log', 'resource_key',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='资源标识，如 ETF 代码或指数代码',
               existing_nullable=False)
    op.alter_column('source_payload_log', 'resource_type',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='资源类型，如 daily_bar、share_snapshot',
               existing_nullable=False)
    op.alter_column('source_payload_log', 'source_name',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='数据源名称，如 tencent、eastmoney',
               existing_nullable=False)
    op.alter_column('source_payload_log', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('signal_definition', 'version',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='信号版本号',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0.0'::character varying"))
    op.alter_column('signal_definition', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='信号含义和使用说明',
               existing_nullable=False)
    op.alter_column('signal_definition', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='信号中文名称',
               existing_nullable=False)
    op.alter_column('signal_definition', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='产生该信号的策略 ID',
               existing_nullable=False)
    op.alter_column('signal_definition', 'signal_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='信号唯一标识，如 three_factor_signal',
               existing_nullable=False)
    op.alter_column('research_run_item', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='单个 ETF 处理指标，如因子值、信号得分等',
               existing_nullable=True)
    op.alter_column('research_run_item', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='处理结果说明或错误信息',
               existing_nullable=True)
    op.alter_column('research_run_item', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='单个 ETF 处理状态：success=成功，failed=失败，skipped=跳过',
               existing_nullable=False)
    op.alter_column('research_run_item', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='处理的 ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('research_run_item', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='所属运行 ID，外键关联 research_run',
               existing_nullable=False)
    op.alter_column('research_run_item', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('research_run', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='运行结束时间（UTC），NULL 表示未完成',
               existing_nullable=True)
    op.alter_column('research_run', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='运行开始时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('research_run', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='失败时的错误信息',
               existing_nullable=True)
    op.alter_column('research_run', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='运行结果指标，如处理 ETF 数量、耗时等',
               existing_nullable=True)
    op.alter_column('research_run', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='运行参数，JSON 格式',
               existing_nullable=True)
    op.alter_column('research_run', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='运行状态：pending=待执行，running=执行中，success=成功，failed=失败',
               existing_nullable=False)
    op.alter_column('research_run', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='运行对应的交易日期',
               existing_nullable=True)
    op.alter_column('research_run', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='关联策略 ID，仅 strategy_run 类型有值',
               existing_nullable=True)
    op.alter_column('research_run', 'run_type',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='运行类型：daily_ingest=日频入库，strategy_run=策略运行，universe_refresh=标的刷新',
               existing_nullable=False)
    op.alter_column('research_run', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='运行唯一 ID，UUID 格式',
               existing_nullable=False)
    op.alter_column('index_daily_bar', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='数据入库时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('index_daily_bar', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='数据来源，stub=占位数据',
               existing_nullable=False,
               existing_server_default=sa.text("'stub'::character varying"))
    op.alter_column('index_daily_bar', 'turnover',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成交额，单位 元',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成交量，单位 手',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'change_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='涨跌幅，单位 %',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'prev_close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='前收盘点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='收盘点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'low_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最低点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'high_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最高点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='开盘点位',
               existing_nullable=True)
    op.alter_column('index_daily_bar', 'index_code',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='指数代码，外键关联 benchmark_index',
               existing_nullable=False)
    op.alter_column('index_daily_bar', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('index_daily_bar', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('factor_definition', 'owner_plugin',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='定义该因子的策略插件 ID',
               existing_nullable=False)
    op.alter_column('factor_definition', 'version',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='因子版本号，遵循语义化版本',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0.0'::character varying"))
    op.alter_column('factor_definition', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='因子计算逻辑说明',
               existing_nullable=False)
    op.alter_column('factor_definition', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='因子中文名称，如 20日量比',
               existing_nullable=False)
    op.alter_column('factor_definition', 'factor_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='因子唯一标识，如 volume_ratio_20d',
               existing_nullable=False)
    op.alter_column('etf_universe', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录最后更新时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_universe', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_universe', 'data_source',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='数据来源，seed=内置种子数据',
               existing_nullable=False,
               existing_server_default=sa.text("'seed'::character varying"))
    op.alter_column('etf_universe', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否在交易中，退市后置 False',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('etf_universe', 'is_a_share_etf',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为 A 股 ETF',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('etf_universe', 'category',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='ETF 分类，如 broad_index=宽基指数',
               existing_nullable=False,
               existing_server_default=sa.text("'broad_index'::character varying"))
    op.alter_column('etf_universe', 'delisting_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='退市日期，NULL 表示仍在交易',
               existing_nullable=True)
    op.alter_column('etf_universe', 'listing_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='上市日期',
               existing_nullable=True)
    op.alter_column('etf_universe', 'fund_company',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='基金管理公司名称',
               existing_nullable=True)
    op.alter_column('etf_universe', 'tracking_index_name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='跟踪指数名称，如 沪深300',
               existing_nullable=False)
    op.alter_column('etf_universe', 'tracking_index_code',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='跟踪指数代码，如 000300',
               existing_nullable=True)
    op.alter_column('etf_universe', 'fund_full_name',
               existing_type=sa.VARCHAR(length=256),
               comment=None,
               existing_comment='基金全称',
               existing_nullable=True)
    op.alter_column('etf_universe', 'name_cn',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='ETF 中文简称',
               existing_nullable=False)
    op.alter_column('etf_universe', 'exchange',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='交易所代码，SSE=上交所，SZSE=深交所',
               existing_nullable=False)
    op.alter_column('etf_universe', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='ETF 代码，如 510300',
               existing_nullable=False)
    op.alter_column('etf_signal', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='产生该信号的研究运行 ID，NULL 表示手动触发',
               existing_nullable=True)
    op.alter_column('etf_signal', 'signal_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='信号计算明细，包含各因子得分等中间数据',
               existing_nullable=True)
    op.alter_column('etf_signal', 'signal_label',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='信号中文标签，如 高确信、中等关注、正常',
               existing_nullable=False)
    op.alter_column('etf_signal', 'signal_level',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='信号等级：HIGH≥70，MID 50-69，LOW<50',
               existing_nullable=False)
    op.alter_column('etf_signal', 'signal_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='综合得分，0-100，越高表示信号越强',
               existing_nullable=False)
    op.alter_column('etf_signal', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='产生该信号的策略 ID',
               existing_nullable=False)
    op.alter_column('etf_signal', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('etf_signal', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='信号对应的交易日期',
               existing_nullable=False)
    op.alter_column('etf_signal', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_factor_value', 'strategy_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='产生该因子值的策略 ID，NULL 表示通用因子',
               existing_nullable=True)
    op.alter_column('etf_factor_value', 'factor_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='因子计算中间数据，用于调试和解释',
               existing_nullable=True)
    op.alter_column('etf_factor_value', 'factor_value_text',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='因子文本值，用于枚举类因子',
               existing_nullable=True)
    op.alter_column('etf_factor_value', 'factor_value_numeric',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='因子数值，如量比 1.92、概率得分 78.5',
               existing_nullable=True)
    op.alter_column('etf_factor_value', 'factor_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='因子 ID，外键关联 factor_definition',
               existing_nullable=False)
    op.alter_column('etf_factor_value', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('etf_factor_value', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('etf_factor_value', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_daily_share', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='数据入库时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_daily_share', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='数据来源，eastmoney=东方财富，stub=占位数据',
               existing_nullable=False,
               existing_server_default=sa.text("'stub'::character varying"))
    op.alter_column('etf_daily_share', 'aum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='资产管理规模（AUM），单位 亿元',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'nav',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='单位净值，单位 元/份',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'shares_delta_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='当日份额变化率，单位 %',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'shares_delta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='当日份额变化量，单位 亿份，正=申购，负=赎回',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'shares_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='总份额，单位 亿份',
               existing_nullable=True)
    op.alter_column('etf_daily_share', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('etf_daily_share', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('etf_daily_share', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('etf_daily_bar', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='数据入库时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('etf_daily_bar', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='数据来源，tencent=腾讯，stub=占位数据',
               existing_nullable=False,
               existing_server_default=sa.text("'stub'::character varying"))
    op.alter_column('etf_daily_bar', 'amplitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='振幅，单位 %',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'turnover',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成交额，单位 元',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成交量，单位 手（100 股）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'change_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='涨跌幅，单位 %，如 1.23 表示涨 1.23%',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'prev_close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='前收盘价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='收盘价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'low_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最低价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'high_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最高价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='开盘价（前复权）',
               existing_nullable=True)
    op.alter_column('etf_daily_bar', 'etf_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='ETF 代码，外键关联 etf_universe',
               existing_nullable=False)
    op.alter_column('etf_daily_bar', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('etf_daily_bar', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('benchmark_index', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录最后更新时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmark_index', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录创建时间（UTC）',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmark_index', 'exchange',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='所属市场，CN=中国 A 股',
               existing_nullable=False,
               existing_server_default=sa.text("'CN'::character varying"))
    op.alter_column('benchmark_index', 'name_cn',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='指数中文名称，如 沪深300',
               existing_nullable=False)
    op.alter_column('benchmark_index', 'index_code',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='指数代码，如 000300',
               existing_nullable=False)
    # ### end Alembic commands ###
